# Generated by Django 5.2.10 on 2026-01-21 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InfluxDB',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('namespace', models.CharField(default='schema-api', max_length=64)),
                ('pod_modeler_name', models.CharField(max_length=128)),
                ('svc_modeler_name', models.CharField(max_length=128)),
                ('pod_listener_name', models.CharField(max_length=128)),
                ('influx_in', models.JSONField()),
                ('influx_out', models.JSONField()),
                ('modeler', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_runtime', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(default='created', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
